Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'config')

src = Split("""



""")


CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('config', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
