Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'services')
src = Split("""
cJSON.c
JSON_config.c
COM_if.c
GPRS_server.c
sw_crc.c
IOT_analog_in.c
IOT_digit_in.c
IOT_digit_out.c

""")


CPPPATH = [cwd, str(Dir('#'))]


group = DefineGroup('services', src, depend = [''], CPPPATH = CPPPATH)

Return('group')