Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')

# add the general APPs.
src = Split("""
application.c
selftest.c
UITD_main.c
UITD_eth.c
startup.c
sys_misc.c
UITD.c
sys_status.c
sensor_sample.c
fire_alarm.c
controller.c
sntp.c
UITD_BLE.c
UITD_WIFI.c
transparent.c
pro_ctrl.c
pro_UITD.c

""")



CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
